### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ErrorDoc404** [ErrorDoc404/LavaWebsite#4]
- [ ] Server join
- [ ] add button in home page
- [ ] all information about each guild
- [ ] add /play command
- [ ] add /queue command
- [ ] solve no provile image for crash
- [ ] add feature for no setup play
- [ ] make ticket system in server
- [ ] server validation
